//go:build !ignore_autogenerated

// Copyright (C) 2026 Red Hat, Inc.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSecretReference) DeepCopyInto(out *CredentialSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSecretReference.
func (in *CredentialSecretReference) DeepCopy() *CredentialSecretReference {
	if in == nil {
		return nil
	}
	out := new(CredentialSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetIdentity) DeepCopyInto(out *TargetIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetIdentity.
func (in *TargetIdentity) DeepCopy() *TargetIdentity {
	if in == nil {
		return nil
	}
	out := new(TargetIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationArtifactReference) DeepCopyInto(out *ValidationArtifactReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationArtifactReference.
func (in *ValidationArtifactReference) DeepCopy() *ValidationArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ValidationArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationReportReduction) DeepCopyInto(out *ValidationReportReduction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationReportReduction.
func (in *ValidationReportReduction) DeepCopy() *ValidationReportReduction {
	if in == nil {
		return nil
	}
	out := new(ValidationReportReduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationReportStatus) DeepCopyInto(out *ValidationReportStatus) {
	*out = *in
	out.Reduction = in.Reduction
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationReportStatus.
func (in *ValidationReportStatus) DeepCopy() *ValidationReportStatus {
	if in == nil {
		return nil
	}
	out := new(ValidationReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationRun) DeepCopyInto(out *ValidationRun) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationRun.
func (in *ValidationRun) DeepCopy() *ValidationRun {
	if in == nil {
		return nil
	}
	out := new(ValidationRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationStep) DeepCopyInto(out *ValidationStep) {
	*out = *in
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationStep.
func (in *ValidationStep) DeepCopy() *ValidationStep {
	if in == nil {
		return nil
	}
	out := new(ValidationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationSubjectReference) DeepCopyInto(out *ValidationSubjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationSubjectReference.
func (in *ValidationSubjectReference) DeepCopy() *ValidationSubjectReference {
	if in == nil {
		return nil
	}
	out := new(ValidationSubjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationTarget) DeepCopyInto(out *ValidationTarget) {
	*out = *in
	out.CredentialsSecret = in.CredentialsSecret
	out.Identity = in.Identity
	if in.ToolDownloads != nil {
		in, out := &in.ToolDownloads, &out.ToolDownloads
		*out = new(ValidationToolDownloads)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationTarget.
func (in *ValidationTarget) DeepCopy() *ValidationTarget {
	if in == nil {
		return nil
	}
	out := new(ValidationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationToolDownloads) DeepCopyInto(out *ValidationToolDownloads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationToolDownloads.
func (in *ValidationToolDownloads) DeepCopy() *ValidationToolDownloads {
	if in == nil {
		return nil
	}
	out := new(ValidationToolDownloads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationWorkload) DeepCopyInto(out *ValidationWorkload) {
	*out = *in
	out.DataSource = in.DataSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationWorkload.
func (in *ValidationWorkload) DeepCopy() *ValidationWorkload {
	if in == nil {
		return nil
	}
	out := new(ValidationWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidation) DeepCopyInto(out *VirtualizationValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidation.
func (in *VirtualizationValidation) DeepCopy() *VirtualizationValidation {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualizationValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidationExecution) DeepCopyInto(out *VirtualizationValidationExecution) {
	*out = *in
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(ValidationSubjectReference)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]ValidationStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidationExecution.
func (in *VirtualizationValidationExecution) DeepCopy() *VirtualizationValidationExecution {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidationExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidationList) DeepCopyInto(out *VirtualizationValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualizationValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidationList.
func (in *VirtualizationValidationList) DeepCopy() *VirtualizationValidationList {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualizationValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidationSpec) DeepCopyInto(out *VirtualizationValidationSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.Workload = in.Workload
	out.Run = in.Run
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidationSpec.
func (in *VirtualizationValidationSpec) DeepCopy() *VirtualizationValidationSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidationStatus) DeepCopyInto(out *VirtualizationValidationStatus) {
	*out = *in
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(ValidationReportStatus)
		**out = **in
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ValidationArtifactReference)
		**out = **in
	}
	out.Reduction = in.Reduction
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	out.Summary = in.Summary
	if in.Executions != nil {
		in, out := &in.Executions, &out.Executions
		*out = make([]VirtualizationValidationExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidationStatus.
func (in *VirtualizationValidationStatus) DeepCopy() *VirtualizationValidationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationValidationSummary) DeepCopyInto(out *VirtualizationValidationSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationValidationSummary.
func (in *VirtualizationValidationSummary) DeepCopy() *VirtualizationValidationSummary {
	if in == nil {
		return nil
	}
	out := new(VirtualizationValidationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDataSourceReference) DeepCopyInto(out *WorkloadDataSourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDataSourceReference.
func (in *WorkloadDataSourceReference) DeepCopy() *WorkloadDataSourceReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadDataSourceReference)
	in.DeepCopyInto(out)
	return out
}
